session_name: arunalabru
windows:
  - window_name: bash
    panes:
      - shell_command:
        - source venv/bin/activate
  - window_name: vim
    panes:
      - shell_command:
        - source venv/bin/activate
        - vim
  - window_name: misc
    panes:
      - shell_command:
        - source venv/bin/activate
        - ./manage.py runserver
